
[env]
TERM = "tmux-256color"

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
decorations = "buttonless"
dynamic_padding = true
dynamic_title = true
option_as_alt = "Both"
startup_mode = "Windowed"

[window.padding]
x = 8
y = 8

[general]
live_config_reload = true
import = [
  "~/.config/alacritty/themes/catppuccin-mocha.toml",
  "~/.config/alacritty/fonts.toml",
  "~/.config/alacritty/key-bindings.toml",
]

[terminal]
[terminal.shell]
args = ["--login", "--command", "tmux new-session -A -D -s main"]
program = "/opt/homebrew/bin/fish"
